<?php
// This script and data application were generated by AppGini 5.71
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/memberInfo.php");
	include("$currDir/memberInfo_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('memberInfo');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "memberInfo";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`memberInfo`.`id`" => "id",
		"`memberInfo`.`fname`" => "fname",
		"`memberInfo`.`lname`" => "lname",
		"`memberInfo`.`suffix`" => "suffix",
		"`memberInfo`.`middle`" => "middle",
		"`memberInfo`.`memberDate`" => "memberDate",
		"`memberInfo`.`homePhone`" => "homePhone",
		"`memberInfo`.`workPhone`" => "workPhone",
		"`memberInfo`.`mobilePhone`" => "mobilePhone",
		"`memberInfo`.`emailPreferred`" => "emailPreferred",
		"`memberInfo`.`emailOther`" => "emailOther",
		"`memberInfo`.`addressLine1`" => "addressLine1",
		"`memberInfo`.`addressLine2`" => "addressLine2",
		"`memberInfo`.`city`" => "city",
		"`memberInfo`.`state`" => "state",
		"`memberInfo`.`zip`" => "zip"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`memberInfo`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`memberInfo`.`id`" => "id",
		"`memberInfo`.`fname`" => "fname",
		"`memberInfo`.`lname`" => "lname",
		"`memberInfo`.`suffix`" => "suffix",
		"`memberInfo`.`middle`" => "middle",
		"`memberInfo`.`memberDate`" => "memberDate",
		"`memberInfo`.`homePhone`" => "homePhone",
		"`memberInfo`.`workPhone`" => "workPhone",
		"`memberInfo`.`mobilePhone`" => "mobilePhone",
		"`memberInfo`.`emailPreferred`" => "emailPreferred",
		"`memberInfo`.`emailOther`" => "emailOther",
		"`memberInfo`.`addressLine1`" => "addressLine1",
		"`memberInfo`.`addressLine2`" => "addressLine2",
		"`memberInfo`.`city`" => "city",
		"`memberInfo`.`state`" => "state",
		"`memberInfo`.`zip`" => "zip"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`memberInfo`.`id`" => "ID",
		"`memberInfo`.`fname`" => "First Name",
		"`memberInfo`.`lname`" => "Last Name",
		"`memberInfo`.`suffix`" => "Suffix",
		"`memberInfo`.`middle`" => "Middle",
		"`memberInfo`.`memberDate`" => "Member Since Date",
		"`memberInfo`.`homePhone`" => "Home Phone",
		"`memberInfo`.`workPhone`" => "Work Phone",
		"`memberInfo`.`mobilePhone`" => "Mobile Phone",
		"`memberInfo`.`emailPreferred`" => "EmailPreferred",
		"`memberInfo`.`emailOther`" => "EmailOther",
		"`memberInfo`.`addressLine1`" => "AddressLine1",
		"`memberInfo`.`addressLine2`" => "AddressLine2",
		"`memberInfo`.`city`" => "City",
		"`memberInfo`.`state`" => "State",
		"`memberInfo`.`zip`" => "Zip"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`memberInfo`.`id`" => "id",
		"`memberInfo`.`fname`" => "fname",
		"`memberInfo`.`lname`" => "lname",
		"`memberInfo`.`suffix`" => "suffix",
		"`memberInfo`.`middle`" => "middle",
		"`memberInfo`.`memberDate`" => "memberDate",
		"`memberInfo`.`homePhone`" => "homePhone",
		"`memberInfo`.`workPhone`" => "workPhone",
		"`memberInfo`.`mobilePhone`" => "mobilePhone",
		"`memberInfo`.`emailPreferred`" => "emailPreferred",
		"`memberInfo`.`emailOther`" => "emailOther",
		"`memberInfo`.`addressLine1`" => "addressLine1",
		"`memberInfo`.`addressLine2`" => "addressLine2",
		"`memberInfo`.`city`" => "city",
		"`memberInfo`.`state`" => "state",
		"`memberInfo`.`zip`" => "zip"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`memberInfo` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "memberInfo_view.php";
	$x->RedirectAfterInsert = "memberInfo_view.php?SelectedID=#ID#";
	$x->TableTitle = "MemberInfo";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`memberInfo`.`id`";

	$x->ColWidth   = array(  75, 75, 30, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("First Name", "Last Name", "Suffix", "Middle", "Member Since Date", "Home Phone", "Work Phone", "Mobile Phone", "EmailPreferred", "EmailOther", "AddressLine1", "AddressLine2", "City", "State", "Zip");
	$x->ColFieldName = array('fname', 'lname', 'suffix', 'middle', 'memberDate', 'homePhone', 'workPhone', 'mobilePhone', 'emailPreferred', 'emailOther', 'addressLine1', 'addressLine2', 'city', 'state', 'zip');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16);

	// template paths below are based on the app main directory
	$x->Template = 'templates/memberInfo_templateTV.html';
	$x->SelectedTemplate = 'templates/memberInfo_templateTVS.html';
	$x->TemplateDV = 'templates/memberInfo_templateDV.html';
	$x->TemplateDVP = 'templates/memberInfo_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `memberInfo`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='memberInfo' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `memberInfo`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='memberInfo' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`memberInfo`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: memberInfo_init
	$render=TRUE;
	if(function_exists('memberInfo_init')){
		$args=array();
		$render=memberInfo_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: memberInfo_header
	$headerCode='';
	if(function_exists('memberInfo_header')){
		$args=array();
		$headerCode=memberInfo_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: memberInfo_footer
	$footerCode='';
	if(function_exists('memberInfo_footer')){
		$args=array();
		$footerCode=memberInfo_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>